// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdLzkc8s4mHjlzTJiuaffoOe58NIj22PI',
    appId: '1:740668299225:web:4c78f6228f594fe93e2bc8',
    messagingSenderId: '740668299225',
    projectId: 'device-streaming-afcd4a82',
    authDomain: 'device-streaming-afcd4a82.firebaseapp.com',
    storageBucket: 'device-streaming-afcd4a82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD13MfsSKsj6PUOYjU_6Q6rMOyxE0BrYEg',
    appId: '1:740668299225:android:5ed7a3d1144195083e2bc8',
    messagingSenderId: '740668299225',
    projectId: 'device-streaming-afcd4a82',
    storageBucket: 'device-streaming-afcd4a82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC294eBIYPmxYap5bingf6uSyprKa2ppME',
    appId: '1:740668299225:ios:70e440411b25709d3e2bc8',
    messagingSenderId: '740668299225',
    projectId: 'device-streaming-afcd4a82',
    storageBucket: 'device-streaming-afcd4a82.firebasestorage.app',
    androidClientId: '740668299225-52dp5mp852pv7lot7ecds3a1qkt4p4bj.apps.googleusercontent.com',
    iosClientId: '740668299225-4899onvtg6a67liab2ipkcma14j8leup.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC294eBIYPmxYap5bingf6uSyprKa2ppME',
    appId: '1:740668299225:ios:70e440411b25709d3e2bc8',
    messagingSenderId: '740668299225',
    projectId: 'device-streaming-afcd4a82',
    storageBucket: 'device-streaming-afcd4a82.firebasestorage.app',
    androidClientId: '740668299225-52dp5mp852pv7lot7ecds3a1qkt4p4bj.apps.googleusercontent.com',
    iosClientId: '740668299225-4899onvtg6a67liab2ipkcma14j8leup.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdLzkc8s4mHjlzTJiuaffoOe58NIj22PI',
    appId: '1:740668299225:web:68495ce4b5e7c7bb3e2bc8',
    messagingSenderId: '740668299225',
    projectId: 'device-streaming-afcd4a82',
    authDomain: 'device-streaming-afcd4a82.firebaseapp.com',
    storageBucket: 'device-streaming-afcd4a82.firebasestorage.app',
  );
}
